export { default as FontawesomeIcon } from './fortawesome-icon/index.vue'
export { default as LanguageDropdown } from './language-dropdown/index.vue'
export { default as ParallaxScrolling } from './parallax-scrolling/index.vue'
export { default as SplideCarousel } from './splide-carousel/index.vue'
export { default as BrandsSvg } from './brands-svg/index.vue'
